from __future__ import annotations

MS_PER_ROW_DURATION = 400  # 一行内两张图片的时间间隔(ms)
ROW_COUNT = 5  # 行的数量
IMAGES_PER_ROW = 8  # 每行内图片数量
IMAGE_WIDTH = 512  # 每张预览图片宽度
IMAGE_HEIGHT = 384  # 每张预览图片高度
HORIZONTAL_PAGE_MARGIN = 20  # 图片左右外边距
VERTICAL_PAGE_MARGIN = 20  # 图片上下外边距
INTRA_ROW_IMAGE_GAP = 20  # 一行内两张图片之间间距
INTER_ROW_GAP = 100  # 行与行之间间距
LEFT_PANEL_WIDTH = 12  # 每张图片左侧区域宽度
LEFT_PANEL_BACKGROUND_COLOR = (112, 112, 112, 255)  # 每张图片左侧区域背景色
CANVAS_BACKGROUND_COLOR = (0, 0, 0, 255)  # 整体背景色
IMAGE_BACKGROUND_COLOR = (0, 0, 0, 255)  # 每张图片背景色

PLAYFIELD_WIDTH = 512  # osu!standard 原始游玩区域宽度
PLAYFIELD_HEIGHT = 384  # osu!standard 原始游玩区域高度
PLAYFIELD_VIEWPORT_RATIO = 0.8  # osu!standard gameplay playfield 在 4:3 视口内的缩放比例
PLAYFIELD_STORYBOARD_SHIFT = 8  # lazer gameplay 为对齐 storyboard 对 playfield 施加的下移量
OBJECT_RADIUS = 64  # osu! 源码中 hit object 基础半径
BROKEN_GAMEFIELD_ROUNDING_ALLOWANCE = 1.00041  # osu!stable 历史圆大小修正
POST_HIT_FADE_MS = 120  # 普通 hit circle 命中后的短暂残留时间
SLIDER_FADE_OUT_MS = 240  # slider 结束后的淡出时间
SPINNER_FADE_OUT_MS = 240  # spinner 结束后的淡出时间
BREAK_GAP_MS = 2200  # 未声明 break 时，将长于此值的无 note 间隔视为 break
BREAK_MIN_DURATION_MS = 650  # osu! BreakPeriod.MIN_BREAK_DURATION，短于此值不产生 break overlay
BREAK_FADE_DURATION_MS = BREAK_MIN_DURATION_MS // 2  # osu! BreakOverlay.BREAK_FADE_DURATION
BREAK_OVERLAY_BAR_WIDTH_RATIO = 0.3  # osu! break 剩余时间条最大宽度占屏幕比例
BREAK_OVERLAY_BAR_HEIGHT = 8  # osu! break 剩余时间条高度
BREAK_OVERLAY_COUNTER_FONT_SIZE = 33  # osu! RemainingTimeCounter 数字字号
BREAK_OVERLAY_INFO_FONT_SIZE = 18  # 图片中央 break 时间说明字号
BREAK_OVERLAY_INFO_TOP_GAP = 14  # 剩余时间条与 break 时间说明之间的间距
BREAK_OVERLAY_COLOR = (238, 238, 238, 255)  # break overlay 主文字颜色
BREAK_OVERLAY_INFO_COLOR = (185, 185, 185, 255)  # break 时间说明颜色
TIME_LABEL_FONT_SIZE = 30  # 时间标签字号，约为 PIL 默认字号的三倍
TIME_LABEL_NOTE_FONT_SIZE = 22  # 时间标签备注字号，用于 PreviewTime 说明
TIME_LABEL_HEIGHT = 76  # 时间标签预留高度，包含主时间和可选备注
TIME_LABEL_TOP_GAP = 8  # 图片与时间标签之间的间距
TIME_LABEL_NOTE_TOP_GAP = 9  # 主时间与备注之间的间距
TIME_LABEL_COLOR = (232, 232, 232, 255)  # 时间标签文字颜色
TIME_LABEL_NOTE_COLOR = (170, 170, 170, 255)  # 时间标签备注文字颜色
PREVIEW_TIME_LABEL_COLOR = (95, 221, 108, 255)  # PreviewTime 所在时间标签和备注颜色
SLIDER_BORDER_WIDTH = 6  # slider 轨道边框宽度
SLIDER_BODY_SUPERSAMPLE = 3  # slider body 临时高分辨率绘制倍数，减少曲线接缝
SLIDER_LEGACY_BORDER_PORTION = 0.1875  # osu!stable legacy slider body 边框在半径中的占比
SLIDER_LEGACY_TRACK_ALPHA = 0.7  # legacy slider track override 固定透明度
SLIDER_LEGACY_SHADOW_ALPHA = 0.25  # legacy slider body 外侧阴影透明度
SNAKING_IN_SLIDERS = True  # 对应 osu! 设置项 Snaking in sliders 打开
SNAKING_OUT_SLIDERS = True  # 对应 osu! 设置项 Snaking out sliders 打开
